[semver:patch]

diff --git a/src/commands/build_archive.yml b/src/commands/build_archive.yml
--- a/src/commands/build_archive.yml
+++ b/src/commands/build_archive.yml
@@ -4,15 +4,15 @@ steps:
   - attach_workspace:
       at: workspace
   - run:
-    name: Set Python
-    command: |
-      if ! pyenv -v COMMAND &> /dev/null
-      then
-          echo "pyenv could not be found"
-          exit
-      else
-          pyenv global 3.6.5
-      fi
+      name: Set Python
+      command: |
+        if ! pyenv -v COMMAND &> /dev/null
+        then
+            echo "pyenv could not be found"
+            exit
+        else
+            pyenv global 3.6.5
+        fi
   - run:
       name: Create Workspace Build directory.
       command: mkdir -p workspace/build
